// <auto-generated />
namespace DeltaSigmaPhiWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Rooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rooms));
        
        string IMigrationMetadata.Id
        {
            get { return "201504230109432_Rooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
