// <auto-generated />
namespace Dsp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FundraiserExternalControl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FundraiserExternalControl));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191637314_FundraiserExternalControl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
