// <auto-generated />
namespace Dsp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Philanthropy3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Philanthropy3));
        
        string IMigrationMetadata.Id
        {
            get { return "201801160331190_Philanthropy3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
