//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaSigmaPhiWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ChoreAssignment> ChoreAssignments { get; set; }
        public virtual DbSet<ChoreClass> ChoreClasses { get; set; }
        public virtual DbSet<ChoreGroup> ChoreGroups { get; set; }
        public virtual DbSet<ChoreGroupType> ChoreGroupTypes { get; set; }
        public virtual DbSet<Chore> Chores { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassesTaken> ClassesTakens { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<IncidentReport> IncidentReports { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<LaundrySignup> LaundrySignups { get; set; }
        public virtual DbSet<Leader> Leaders { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberStatu> MemberStatus { get; set; }
        public virtual DbSet<OrganizationPosition> OrganizationPositions { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationsJoined> OrganizationsJoineds { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
        public virtual DbSet<PledgeClass> PledgeClasses { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<ServiceHour> ServiceHours { get; set; }
        public virtual DbSet<SoberDriverSignup> SoberDriverSignups { get; set; }
        public virtual DbSet<SoberOfficerSignup> SoberOfficerSignups { get; set; }
        public virtual DbSet<StudyHour> StudyHours { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
