//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaSigmaPhiWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoberOfficerSignup
    {
        public int UserId { get; set; }
        public System.DateTime DateTimeShift { get; set; }
        public System.DateTime DateTimeSignedUp { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
